  db:
    image: postgres:latest
    volumes:
      - ./migration/migration_file.sql:/docker-endtrypoint-initdb.d/cp.sql
      - ./db:/var/lib/postgresql/data
    container_name: postgresql_container_name
    env_file:
      - ./.env
    ports:
      - ${db_port}:5432
    environment:
      - POSTGRES_USER=${db_user}
      - POSTGRES_DB=${db_name}
      - POSTGRES_PASSWORD=${db_password}
    restart: unless-stopped
